apiVersion: v1
kind: Pod
metadata: 
    name: basic-pod
    labels:
      app: basic-pod
spec:
    containers:
      - name: nginx
        image:  nginx:latest
        ports:
        - containerPort: 80
